### ISSUE TITLE
Investigate updating of statistics

### ISSUE THREAD

**Issue by foolo** [zkemail/dkim-lookup#39]
Yush G, [2024-02-24 23:57]
how close is https://registry.prove.email/statistics to real-time? i.e. how long after someone sees “new pair found” on their side, will this page update? it’s been about 1.5 hours since ive been adding selectors but i see no changes on the statistics page, even though i see new domains

**Comment by foolo** [comment]
@Divide-By-0 Now there is a revalidation time of 60 seconds instead of Infinity :)
https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#revalidate

**Comment by Divide-By-0** [comment]
> @Divide-By-0 Now there is a cache revalidation time of 60 seconds instead of Infinity :) https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#revalidate
> 
> Also note that with the way revalidation works in Next.js, the first time you refresh the page after a 60 second window, it will show the **old** data and trigger a revalidation, then it will show the new data on next refresh, which means that you may need to refresh the browser **twice** to be sure to see the latest data. To avoid this, I think one would need to disable caching completely, but then the database would be queried every time someone visits the page.

The double refresh seems fine! The numbers don't need to be exact.
